### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by soredake** [angelXwind/OpenSyobonAction#10]
would be nice to have one

**Comment by soredake** [comment]
@angelXwind

**Comment by soredake** [comment]
@Lin-Buo-Ren

**Comment by RealPortalPlayer** [comment]
the last commit was 4 years ago
i doubt this project is still alive

**Comment by soredake** [comment]
Dead or not, package for flatpak can be built.

**Comment by brlin-tw** [comment]
Apologies for the ignorance, although I have no issue with Flatpak I'm currently not able to invest any time in it.

**Comment by eugenioLR** [comment]
i'm currently modifying the game, if you want i could do it with my version

**Comment by soredake** [comment]
> i'm currently modifying the game, if you want i could do it with my version

It would be nice!
